- name: Check and install Nginx on Ubuntu servers
  hosts: linux-web
  become: yes  # Sử dụng quyền sudo
  become_user: testuser  # Chạy các lệnh dưới quyền testuser
  gather_facts: yes

  tasks:
    - name: Check if Nginx is installed
      ansible.builtin.command: command -v nginx
      register: nginx_check
      failed_when: false
      changed_when: false

    - name: Print Nginx installation status
      ansible.builtin.debug:
        msg: >
          {% if nginx_check.rc == 0 %}
          Nginx is already installed.
          {% else %}
          Nginx is not installed.
          {% endif %}

    - name: Install Nginx if not installed
      ansible.builtin.command:
        cmd: sudo apt-get install -y nginx
      when: nginx_check.rc != 0

    - name: Ensure Nginx service is running and enabled
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
      when: nginx_check.rc != 0
